### ISSUE TITLE
Pyotp Module Error in mod_mfa.py

### ISSUE THREAD

**Issue by n0n0peration** [yezz123/Athena#23]
After stepping through the installation process and install pyotp I receive the below error:

sudo python3.8 Athena.py 
Traceback (most recent call last):
  File "Athena.py", line 11, in <module>
    from mod_mfa import mod_mfa
  File "/home/n0ps/Athena/bad/mod_mfa.py", line 4, in <module>
    import pyotp
ModuleNotFoundError: No module named 'pyotp'

**Comment by yezz123** [comment]
hello @n0n0peration thank you for informing me, please could you give me more information about your environment or you can try `pip install pyotp`

**Comment by n0n0peration** [comment]
Appears to have worked though yesterday did not. Thanks for the resolution.

**Comment by yezz123** [comment]
welcome thanks for informing me 🚀
